### ISSUE TITLE
Cannot read property 'pickAlgorithm' of null

### ISSUE THREAD

**Issue by gitcloned** [npm/ssri#27]
Hi 

I am doing a npm install of a custom package, which internally is using ssri, and is failing at below line:

```shell
3672 timing reifyNode:node_modules/rxjs Completed in 11639ms
3673 timing reify:rollback:createSparse Completed in 7383ms
3674 timing reify:rollback:retireShallow Completed in 0ms
3675 timing command:install Completed in 31124ms
3676 verbose stack TypeError: Cannot read property 'pickAlgorithm' of null
3676 verbose stack     at Integrity.match (C:\Users\srvacctivpreal\AppData\Roaming\npm\node_modules\npm\node_modules\ssri\index.js:234:24)
3676 verbose stack     at CachePolicy.satisfies (C:\Users\srvacctivpreal\AppData\Roaming\npm\node_modules\npm\node_modules\make-fetch-happen\lib\cache\policy.js:113:49)
3676 verbose stack     at Function.find (C:\Users\srvacctivpreal\AppData\Roaming\npm\node_modules\npm\node_modules\make-fetch-happen\lib\cache\entry.js:172:25)
3677 verbose cwd E:\IVPDealPlatform\services\core\apps
3678 verbose Windows_NT 10.0.14393
3679 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\srvacctivpreal\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "file:../../../dependencies/apps/start/start-v3-master-deb.tar.gz"
3680 verbose node v10.22.0
3681 verbose npm  v8.0.0
3682 error Cannot read property 'pickAlgorithm' of null
3683 verbose exit 1
```

Can you please guide to what could be the issue? 

My npm version is: 7.24.2
My node version is: 12.18.3

**Comment by Lucid36** [comment]
- [ ]

**Comment by zomixi** [comment]
same problem, some one can help?

**Comment by wraithgar** [comment]
This would only happen if you asked it to specifically validate with no integrities.  There's not enough here to reproduce the problem locally.  If you have a case that we could use to replicate locally please file a new issue w/ those details.

**Comment by PaulVipond** [comment]
This keeps on happening to me and clearing the cache is painful because all of your globally installed packages disappear. So I did some digging. The issue for me first starts in the 'make-fetch-happen' module:

```  
  // returns true if the policy satisfies the request
  satisfies (request) {
     ...
    if (this.options.integrity) {
      return ssri.parse(this.options.integrity).match(this.entry.integrity)
    }
  }
```
In my case, this.options has an integrity property, but this.entry doesn't. So either here, or further down in the call-stack (SSRI module Integrity.match ssri\lib\index.js:273:24), there needs to be a check for either the fetched entry or the cache entry having no integrity property. Unless that's obviously some kind of fundamental error and plainly shouldn't happen:

```
  match (integrity, opts) {
    // CAN WE CHECK FOR integrity being null here?
    opts = ssriOpts(opts)
    const other = parse(integrity, opts)
    const algo = other.pickAlgorithm(opts)      <--- fails here as integrity is null on entering the function
    return (
      this[algo] &&
      other[algo] &&
      this[algo].find(hash =>
        other[algo].find(otherhash =>
          hash.digest === otherhash.digest
        )
      )
    ) || false
  }

```

In debug, this.options looks like:

```
{
  agent: undefined,
  algorithms: [ 'sha512' ],
  body: undefined,
  cache: 'default',
  cachePath: 'C:\\Users\\Paul\\AppData\\Local\\npm-cache\\_cacache',
  ca: null,
  cert: null,
  headers: {
    'user-agent': 'npm/8.11.0 node/v16.13.1 win32 x64 workspaces/false',
    'pacote-version': '13.5.0',
    'pacote-req-type': 'tarball',
    'pacote-pkg-id': 'remote:lodash.defaults@http://registry.npmjs.org/lodash.defaults/-/lodash.defaults-4.2.0.tgz',
    'pacote-integrity': 'sha512-qjxPLHd3r5DnsdGacqOMU6pb/avJzdh9tFX2ymgoZE27BmjXrNy/y4LoaiTeAb+O3gL8AfpJGtqfX/ae2leYYQ==',
    'npm-command': 'install'
  },
  integrity: Integrity { sha512: [ [Hash] ] },
  key: null,
  localAddress: null,
  maxSockets: 15,
  memoize: undefined,
  method: 'GET',
  noProxy: '',
  proxy: null,
  retry: { retries: 2, factor: 10, maxTimeout: 60000, minTimeout: 10000 },
  timeout: 300000,
  rejectUnauthorized: true,
  dns: { ttl: 300000, lookup: [Function: lookup] }
}
```

And this.entry looks like:

```
{
  key: 'make-fetch-happen:request-cache:http://registry.npmjs.org/lodash.defaults/-/lodash.defaults-4.2.0.tgz',
  integrity: null,
  path: undefined,
  size: '0',
  time: 1653563170687,
  metadata: {
    time: 1653563170687,
    url: 'http://registry.npmjs.org/lodash.defaults/-/lodash.defaults-4.2.0.tgz',
    reqHeaders: {},
    resHeaders: {
      'content-type': 'text/plain;charset=UTF-8',
      date: 'Thu, 26 May 2022 11:06:11 GMT',
      location: 'https://registry.npmjs.org/lodash.defaults/-/lodash.defaults-4.2.0.tgz',
      vary: 'Accept-Encoding'
    },
    status: 301
  }
}
```

**Comment by kingnebby** [comment]
I started getting this on one of my projects as well. Any updates? Clearing the cache works for one project but when I use in another project it fails. I'm using `nvm` and node v16.16.0 (npm v8.15.0). 

```
3996 verbose stack TypeError: Cannot read properties of null (reading 'pickAlgorithm')
3996 verbose stack     at Integrity.match (~/.nvm/versions/node/v16.16.0/lib/node_modules/npm/node_modules/ssri/lib/index.js:273:24)
3996 verbose stack     at CachePolicy.satisfies (~/.nvm/versions/node/v16.16.0/lib/node_modules/npm/node_modules/make-fetch-happen/lib/cache/policy.js:112:49)
3996 verbose stack     at Function.find (~/.nvm/versions/node/v16.16.0/lib/node_modules/npm/node_modules/make-fetch-happen/lib/cache/entry.js:177:25)
3996 verbose stack     at async cacheFetch (~/.nvm/versions/node/v16.16.0/lib/node_modules/npm/node_modules/make-fetch-happen/lib/cache/index.js:8:17)
3996 verbose stack     at async fetch (~/.nvm/versions/node/v16.16.0/lib/node_modules/npm/node_modules/make-fetch-happen/lib/fetch.js:98:7)
```

**Comment by pshahid** [comment]
FYI I was experiencing this issue `npm ERR! npm ERR! Cannot read properties of null (reading 'pickAlgorithm')`
and tracked it down to using `http://registry.npmjs.org` instead of `https://registry.npmjs.org` in `~/.npmrc`. Unfortunately, search results led me down the path of cache clearing, but that is not the fix for me.

Versions are as follows:
```
npm --version
8.5.0
node --version
v16.14.2
```

A symptom of this issue was very obvious in hindsight, I saw these notices when installing for a particular project:

```npm notice Beginning October 4, 2021, all connections to the npm registry - including for package installation - must use TLS 1.2 or higher. You are currently using plaintext http to connect. Please visit the GitHub blog for more information: https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/
```
### Reproducible steps
- `npm set "registry=http://registry.npmjs.org/"`
- `npm cache clear --force`
- `npm ci`

### Fixed for me
- `npm set "registry=https://registry.npmjs.org/"`
- `npm ci`

Hope this helps folks finding this issue through search engines :)
